smpallen99/coherence

- lib/coherence/schema.ex
- priv/templates/coherence.install/controllers/coherence/confirmation_controller.ex
- test/support/migrations.exs
- web/controllers/confirmation_controller.ex
- web/controllers/controller_helpers.ex
Hello, thanks for creating Coherence!
I catched a typo that affects the database columns.
> fixes typo for confirmation_sent_at

- test/controllers/controller_helpers_test.exs
- test/controllers/invitation_controller_test.exs
- test/controllers/rememberable_test.exs
- test/mix/tasks/coherence.install_test.exs
- test/view_helpers_test.exs
Fix unstable tests that depend on Environment configs.
Also removed unused aliases in tests
Fix #56 
Thanks
> Fix unstable tests that depend on Environment configs

- README.md
- priv/templates/coherence.install/models/coherence/user.ex
- test/schema_test.exs
- test/support/schema.exs
Fix the following issue https://github.com/smpallen99/coherence/issues/70
> Validate email format with some minor improvements

- web/views/view_helpers.ex
I faced situation when I need separate sign_in link, didn't find it through codebase.
Any concerns?
> Add sign in link helper

- README.md
Looks like a typo.
Generating --full-invitable excludes confirmable, not registrable.
> Fix readme getting started section

- web/views/view_helpers.ex
Adding another batch of useful helpers, that are often used in templates.
> Add current_user and logged_in? view helpers

- README.md
* Fix this https://github.com/smpallen99/coherence/issues/95
> Update the correct use case of coherence

- lib/coherence/redirects.ex
- priv/templates/coherence.install/templates/coherence/registration/edit.html.eex
- priv/templates/coherence.install/templates/coherence/registration/show.html.eex
- priv/templates/coherence.install/views/coherence/coherence_view_helpers.ex
- test/controllers/registration_controller_test.exs
- web/router.ex
- web/views/view_helpers.ex
Fix this issue https://github.com/smpallen99/coherence/issues/90
> Remove unused params from registration path

- README.md
- lib/coherence/config.ex
- lib/coherence/schema.ex
- priv/templates/coherence.install/controllers/coherence/registration_controller.ex
- priv/templates/coherence.install/templates/coherence/password/edit.html.eex
- priv/templates/coherence.install/templates/coherence/registration/form.html.eex
- test/controllers/controller_helpers_test.exs
- test/controllers/registration_controller_test.exs
- web/controllers/controller_helpers.ex
- web/controllers/registration_controller.ex
- web/models/confirmable.ex
Improve this https://github.com/smpallen99/coherence/issues/107
> Require current password when edit account

- priv/templates/coherence.install/templates/coherence/password/edit.html.eex
Fix this issue https://github.com/smpallen99/coherence/issues/123
> Remove current password when reset new password

- lib/mix/tasks/coherence.make_templates.ex
> Create mix task to make controller templates

- README.md
To make it a little more obvious to people new to elixir/phoenix and a little easier to search.
> Add small doc section about accessing current_user

- priv/templates/coherence.install/coherence_web.ex
- priv/templates/coherence.install/controllers/coherence/confirmation_controller.ex
- priv/templates/coherence.install/controllers/coherence/session_controller.ex
- priv/templates/coherence.install/views/coherence/coherence_view_helpers.ex
- priv/templates/coherence.install/views/coherence/confirmation_view.ex
- priv/templates/coherence.install/views/coherence/email_view.ex
- priv/templates/coherence.install/views/coherence/invitation_view.ex
- priv/templates/coherence.install/views/coherence/layout_view.ex
- priv/templates/coherence.install/views/coherence/password_view.ex
- priv/templates/coherence.install/views/coherence/registration_view.ex
- priv/templates/coherence.install/views/coherence/session_view.ex
- priv/templates/coherence.install/views/coherence/unlock_view.ex
Hi,
thank you very much for this project! I just wanted to get to know it a little better and while reading through the code, I removed some spare empty lines that didn't seem to fit to the rest of the coding style of the project.
I hope you find these changes helpful, if not, please feel free to close the PR.
Best,
Christian
> Removes dispensable empty lines

- lib/coherence/redirects.ex
Simple doc fix for issue #144 
As far as I can tell no code actually needs to change.
> Doc changes for the redirect instructions

- lib/mix/tasks/coherence.install.ex
Fix this issue https://github.com/smpallen99/coherence/issues/139
> Fix unable to reinstall when specified actions are set

- README.md
Adds Elixir syntax highlighting for the Installation section of README.
> update readme:installation elixir syntax highlight

- lib/coherence/redirects.ex
- priv/templates/coherence.install/controllers/coherence/invitation_controller.ex
- web/controllers/invitation_controller.ex
> Callback to redirect invitation resend.

- web/controllers/session_controller.ex
Fixes issue #196 by adding missing parameter.
> Add missing argument to fix invalid login bug

- .travis.yml
Hello again, a quick update copying the settings from ex_admin to test against newer OTP and Elixir.
Thanks
Sam
> Expand Travis build matrix

- priv/templates/coherence.install/emails/coherence/user_email.ex
- priv/templates/coherence.install/views/coherence/coherence_view_helpers.ex
Remove the compiler warnings and fix the credo issues present in the generated code
> Fix credo issues and compilation warnings from generated files

- README.md
> fix a typo in the readme

- lib/coherence/config.ex
Solving the same problem as https://github.com/smpallen99/coherence/pull/238, using the solution I found in `Coherence.ControllerHelpers.send_user_email/3`
EDIT: Working out some kinks with using this version in my own application. Seems like a 1.2 vs 1.3 edge case. I'll keep digging.
> Remove Reference to CoherenceDemo

- README.md
- lib/coherence/controllers/controller_helpers.ex
I needed to use these options to install coherence in a new 1.3 umbrella generated project This is my attempt to update the README to resolve #247
> Adding information about install opts

- README.md
Just I added a basic comment to add the 'pipeline :protected' block manually to the router file.
> Add comment to the README.md

- README.md
[Rendered](https://github.com/gmile/coherence/blob/update-readme/README.md).
> Cosmetic changes to README.md

- README.md
> Put credentials doc fix

- README.md
> Introduces new function update_user_login/1.

- lib/coherence/controllers/password_controller.ex
Check #387 for further information.
> ensure reset_password_token appears when errors happens
