README.md
The model changes seem disjointed where they are; this moves them back up to beneath the introductory paragraph.
=> Relocate model changes to the introductory paragraph

priv/templates/coherence.install/views/coherence/coherence_view_helpers.ex, web/views/view_helpers.ex
Add signout_link to view helpers. I think it might come in handy. Sometime I don't want to use `coherence_links`, it will give more than what I need. With this PR, I can do something like below in the view
```ruby
<%= MyProject.Coherence.ViewHelpers.signout_link(@conn) %>
```
=> Add signout_link function to view helpers

priv/templates/coherence.install/controllers/coherence/session_controller.ex, web/controllers/session_controller.ex
Improvement for this issue https://github.com/smpallen99/coherence/issues/64
Tested and seem work well on my local
=> Give correct HTTP status code when login fail

lib/coherence/plugs/authorization/session.ex
The module resolution in `Session.default_login_callback/0` is non-deterministic. Please refer to my other PR https://github.com/smpallen99/coherence/pull/75.
=> Ensure local module is loaded on login callback

README.md
The email_from value in config is set to email_from: `{"Your Name", "yourname@example.com"},` by default. If this is not changed emails might not go out as expected. Clarifying this in the README will help those that don't edit that value as they first start to wire things up with coherence.
=> Readme Email Config Clarification

lib/coherence/redirects.ex, priv/templates/coherence.install/controllers/coherence/redirects.ex, web/controllers/redirect.ex
Just a typo fix for "ever ride".
=> 'ever ride' -> 'override' typo

README.md
As discussed at #26 adding layout customization section to README.
Also I have a couple proposals:
1. Maybe we should use github wiki for documenting package usage? E.g. [devise gem](https://github.com/plataformatec/devise/wiki) has a rich wiki with examples, guides and example applications. Or, alternatively we could add docs directory to project that will contain *.md files with such information.
2. In my PR I proposed alternative way of customizing layout. It won't break any existing installations of package, so, probably we could merge `web/coherence_web.ex` changes.
@smpallen99 any thoughts?
If you'll accept such solution - I could make separate PR for that.
=> Add templates customization section

lib/coherence.ex
While skimming through the sources I just found a typo (i.e. `conformation`) inside the `@moduledoc` of `coherence.ex`. I suppose it should have been `confirmation`.
=> fix typo in coherence.ex @moduledoc

priv/templates/coherence.install/coherence_web.ex, priv/templates/coherence.install/emails/coherence/coherence_mailer.ex, priv/templates/coherence.install/emails/coherence/user_email.ex, priv/templates/coherence.install/models/coherence/user.ex
A few of the installed templates generate "Modules should have a @moduledoc tag" code readability issues with [credo](https://github.com/rrrene/credo); this fixes them.
=> Modules should have a @moduledoc tag

priv/templates/coherence.install/templates/coherence/session/new.html.eex
Hey, thanks again for this, it’s saved me so much work.
Here‘s a small UX improvement suggestion, making it possible to click the “Remember Me?” text itself to toggle the checkbox in addition to the checkbox itself.
There’s some debate about whether it’s preferable to put the `input` _inside_ the `label`, which I could do if that’s more appealing to you.
This causes the “Remember Me?” text to become bold, hopefully that‘s okay.
=> Make “Remember Me?” clickable

web/controllers/session_controller.ex
before this change, signing in failed with `key :locked_at not found in: %MyApp.User{...` if `lockable` was false.
=> fix session controller when lockable is false

lib/mix/tasks/coherence.install.ex
Removes :trackable option if :trackable_table is present.
Defaults to :trackable for full, full-confirmable and full-invitable options.
=> Removes :trackable option if :trackable_table is present. Fixes #132.

README.md, lib/mix/tasks/coherence.make_templates.ex, priv/templates/coherence.install/emails/coherence/user_email.ex, priv/templates/coherence.install/models/coherence/user.ex
This PR should remove some warings like following in elixir 1.4
```
warning: variable "timestamps" does not exist and is being expanded to "timestamps()",
please use parentheses to remove the ambiguity or change the variable name
```
=> Remove warings about missing parentheses for function calls in elxir 1.4

priv/templates/coherence.install/controllers/coherence/redirects.ex
small doc update: `to:` was missing, and is failing (at least for current phoenix version)
=> set path to redirect to in options

README.md, lib/coherence/schema.ex, lib/mix/tasks/coherence.install.ex, priv/templates/coherence.install/models/coherence/user.ex, test/controllers/password_controller_test.exs, test/support/schema.exs, web/controllers/controller_helpers.ex, web/controllers/password_controller.ex
This is my attempt to solve the bug described in https://github.com/smpallen99/coherence/issues/123
Problem:
The setting `require_current_password` does prevent the resetting of passwords using a token. This is, because at the moment the resetting of a password would require a user to know the current password.
My approach to a solution:
I think the cleanest approach would be to provide an extra `changeset/3` function in the model for this particular use case. This is already possible with the `changeset` config setting, but I think it should be done in any case for the password reset use case.
This is just my first stab at it. I would be happy to get some feedback about this approach. :)
Also, while working in this fix, I stumbled over another bug, which I reported in …
=> Always call a dedicated changeset/3 function for password resets

lib/coherence/config.ex, lib/mix/tasks/coherence.install.ex, web/web.ex
This commit adds support for binary ids in the migrations of the `coherence.install` mix task as already discussed in #125.
Instead of another flag for the installer, I decided to go with the official phoenix configuration which already provides a way to set the way ids are handled by default.
This has some advantages. For example the generated model does not need any special attributes, if the phoenix application is properly configured. You can add the configuration manually in your `config.exs`:
```elixir
config :phoenix, :generators,
binary_id: true
```
or just pass the `--binary-id` flag when bootstrapping a new phoenix application.
```
mix phoenix.new --binary-id
```
If the phoenix application is configured to default to binary ids, the generator of coherence now will respect this …
=> Adds support for binary_ids

lib/coherence/schema.ex
The contributing doc states that every PR should have an issue associated so please just let me know if I need to create one, but I thought maybe it would be just extra noise on the issue tracker for a single character addition docfix. Thanks!
=> Fix function name typo in documentation

lib/coherence/config.ex, lib/coherence/schema.ex, test/schema_test.exs
Added an item `minimum_password_length` in the Coherence Config to support custom minimum password lengths. Default length is 4.
=> Add config option to specify minimum password length Issue#206

lib/mix/tasks/coh.install.ex
The messages backend is actually created in the Web module rather than the base module, this fixes the generated config to reflect that correctly.
=> Messages backend is defined in the web module

lib/coherence/plugs/authorization/session.ex
With the alias inside `get_user_data` the other functions throw errors.
=> Fix alias position in DbStore example

README.md
I just directly copied the code from README and thus installed version 0.4
accidentally, this caused me a lot of headache until I found it out...
Also fixed some typos and formatting.
=> Fixed coherence version from 0.4 to 0.5 in the README file

lib/coherence/plugs/authorization/token.ex
The documentation at https://hexdocs.pm/coherence/Coherence.Authentication.Token.html shows
```elixir
plug Coherence.Authentication.Token, source: :header, param: "X-Auth-Token"
```
as an example configuration for token auth, but plug downcases all headers, so `X-Auth-Token` will never match anything.
=> Fix documentation for token auth

README.md, lib/coherence/config.ex, lib/coherence/router.ex, test/config_test.exs
Hello, I have taken the freedom of creating this PR changing the way coherence handles default routes such as "registrations/edit" and "sessions". 
Coherence will support custom routes for registration and login. These configurations can be set globally or scoped.
Which routes can be customised?
```
%{
registrations_new:  "/registrations/new",
registrations:      "/registrations",
passwords:          "/passwords",
confirmations:      "/confirmations",
unlocks:            "/unlocks",
invitations:        "/invitations",
invitations_create: "/invitations/create",
invitations_resend: "/invitations/:id/resend",
sessions:           "/sessions",
registrations_edit: "/registrations/edit"
}
```
To set them globally you will need to add the following to you configuration:
```elixir
config …
```
=> Feature - Custom routes for registrations and sessions

priv/templates/coh.install/templates/coherence/registration/form.html.eex
#315 
@smpallen99 By changing the boilerplate code we could avoid label inconsistency. Pardon me if I made any mistake in fixing.
=> [#315] Registration labels inconsistency

lib/coherence/controllers/password_controller.ex
Fixed in password controller the action create to generate correctly the URL when the host domain includes a subdomain.
Before the fix we has:
Expected result:
Host: `demo.lvh.me`
`http://demo.lvh.me:4000/passwords/<generated_token>/edit`
Obtained result:
`http://localhost:4000/passwords/<generated_token>/edit`
**Note:** This change no affects the old implementation.
**Note:** I reviewed that this problem does not occur in others actions in the password controller but I do not review it in other controllers.
=> Fixed in password controller the action create to support subdomains

README.md
In a controller, `update_login` works only `Coherence.Config` is used explicitly.
=> Call update_login explicitly.

lib/coherence/controllers/registration_controller.ex, lib/coherence/messages.ex, priv/templates/coh.install/coherence_messages.ex, test/support/messages.exs
When attempting to log in an error would occur as the Html Responder session_create_success expects notice in it's opts and it is never provided.
Added a new "account_created_successfully" message and provided this with the required opts when attempting to log in immediately after creating an account.
=> Fix issue when attempting to immediately log in after registering an account

config/test.exs, lib/coherence/config.ex, lib/coherence/controllers/confirmation_controller.ex, lib/coherence/controllers/controller.ex, lib/coherence/controllers/registration_controller.ex, lib/coherence/schema.ex, lib/mix/mix_utils.ex, priv/templates/coh.gen.controllers/controllers/coherence/confirmation_controller.ex, priv/templates/coh.gen.controllers/controllers/coherence/registration_controller.ex, priv/templates/coh.install/emails/coherence/user_email.ex, priv/templates/coh.install/models/coherence/user.ex, priv/templates/coh.install/templates/coherence/email/reconfirmation.html.eex, test/controllers/confirmation_controller.exs, test/controllers/registration_controller_test.exs, test/support/email.exs, test/support/migrations.exs, test/support/schema.exs, test/support/test_helpers.exs
Hello,
We are using coherence and we need to confirm user email on each update.
We found an issue and saw that the feature is missing but PR are welcome: https://github.com/smpallen99/coherence/issues/74
Here is a PR that add an option to require email update confirmation instead of directly updating the database. We are using the `unconfirmed_email` attributes that was already present on the migration file (but not used in the library)
Can you please make a review on this?
Signed-off-by: Stéphane Robino <stephane@wttj.co>
Signed-off-by: Kévin Lacointe <kevinlacointe@gmail.com>
=> Handle unconfirmed email

mix.exs
`Plug.Conn.get_peer_data/1` is used in /services/trackable_service.ex. This function was not added to Plug.Conn until version 1.6.
=> Add plug 1.6 dependency

lib/coherence/controllers/confirmation_controller.ex, priv/templates/coh.gen.controllers/controllers/coherence/confirmation_controller.ex, test/controllers/confirmation_controller.exs
Hello,
Some improvements
1/ after confirming a new email, the user should be updated in the credential store to refrect updates on the `unconfirmed_email` attribute
2/ allow to resend email confirmation for unconfirmed emails
=> Confirm email updates improvements

lib/coherence/schema.ex
This is useful if you for instance need to support authenticating some users via a legacy password imported from a legacy-database using another hashing-algorithm than your normal passwords.
Example:
```elixir
defmodule Example.Coherence.User do
def checkpw(password, encrypted) do
if encrypted |> String.starts_with?("LEGACY!") do
[_, hash, salt] = String.split(encrypted, "!")
Example.Coherence.LegacyPassword.valid?(hash, salt, password)
else
super(password, encrypted)
end
end
end
defmodule Example.Coherence.LegacyPassword do
@provider :sha512
@stretches 20
def valid?(nil, _salt, _pass), do: false
def valid?(_hash, nil, _pass), do: false
def valid?(hash, salt, pass) do
hash == encrypt(pass <> salt)
end
defp encrypt(string) do
Enum.reduce(1..@stretches, string, fn(_, acc) -> …
```
=> Allow overriding checkpw/2
